linters:
  enable:
    - gosec

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  skip-dirs:
    - vendor
    - third_party
  skip-files:
    - ".*_test\.go$"

issues:
  exclude:
    - "Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked"
    - "Error return value of `tx.Rollback` is not checked"
    - "Error return value of `tx.Commit` is not checked"
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  gosec:
    excludes:
      - G404  # Insecure random number source (rand)
      - G114  # Use of net/http serve function that has no support for setting timeouts