version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - server
  server:
    image: "go8/server"
    container_name: "go8_container"
    env_file:
      - .env
    environment:
      - API_HOST=server
      - DB_HOST=postgres
      - DB_PORT=5432
      - OTEL_OTLP_ENDPOINT=otel-collector:4317
      - REDIS_HOST=valkey
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
