version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - server
  postgres:
    image: postgres:15
    container_name: go8_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=go8_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: go8_redis
    ports:
      - "6379:6379"

  server:
    image: "go8/server"
    container_name: "go8_container"
    env_file:
      - .env
    environment:
      - API_HOST=server
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./.env:/go/src/app/.env
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
