version: '3.8'

services:

  server:
    image: "go8/server"
    container_name: "go8_container"
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - OTEL_OTLP_ENDPOINT=otel-collector:4317
      - REDIS_HOST=redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
