name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.21'
  DOCKER_IMAGE: ngocquan88/go8-server
  DOCKER_TAG: ${{ github.sha }}

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Cache golangci-lint
        uses: actions/cache@v3
        with:
          path: ~/.cache/golangci-lint
          key: ${{ runner.os }}-golangci-${{ hashFiles('.golangci.yml') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-golangci-${{ hashFiles('.golangci.yml') }}-
            ${{ runner.os }}-golangci-
      
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m
          working-directory: .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mail2calendar_test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          
      - name: Clean Go Cache
        run: |
          sudo rm -rf ~/go/pkg/mod
          sudo rm -rf ~/.cache/go-build
          mkdir -p ~/go/pkg/mod
          mkdir -p ~/.cache/go-build
          
      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.mod', 'go.sum') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('go.mod', 'go.sum') }}-
            ${{ runner.os }}-go-
      
      - name: Setup and Download Dependencies
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          go clean -modcache
          go mod download
      
      - name: Run Unit Tests
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASS: password
          DB_NAME: mail2calendar_test_db
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage.txt

  build:
    name: Build and Push Docker Image
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest,${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max

  deploy:
    name: Deploy to Production
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Tailscale
        run: |
          # Install Tailscale non-interactively
          curl -fsSL https://tailscale.com/install.sh | sh -s -- --non-interactive
          
          # Connect with user privileges and operator flag
          tailscale up \
            --authkey ${{ secrets.TAILSCALE_AUTHKEY }} \
            --hostname github-actions-runner \
            --operator=$USER
          
          # Check connection status
          tailscale status

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TAILSCALE_HOST }}  # Using MagicDNS hostname
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd ~/apps/mail2calendar
            docker compose pull
            docker compose up -d